name: Test Punk!

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PUNK_ENV: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Introspect 1
      run: pwd
    - name: Introspect 2
      run: ls -la
    - name: Run tests
      run: bundle exec punk test
