name: ship

on:
  push:
    branches:
      - main

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.8.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "lets-punk"
        heroku_email: "jasonhutchens@gmail.com"
